### ISSUE TITLE
Сделайте актуального php клиента, плз

### ISSUE THREAD

**Issue by tupikoff** [wreckah/target_api#1]

**Comment by tupikoff** [comment]
Сами уже сделали себе) https://github.com/MobioInc/target

**Comment by wreckah** [comment]
@tupikoff молодцы! Напишите про это в фейсбучной группе, чтобы остальные могли пользоваться :)

**Comment by tupikoff** [comment]
https://www.facebook.com/groups/targetmailapi/
Здесь?

**Comment by wreckah** [comment]
Да, там почти все API-пользователи Таргета тусуются.
